@extends('layouts.app', ['activePage' => 'Registros', 'titlePage' => __('Registros')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="row">
    <div class="col-md-12">
        <div class="card" id="tablaAperturas">
          <div class="card-header card-header-info">
            <h4 class="card-title ">Aperturas</h4>
            <p class="card-category"> Registro de aperturas</p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class=" text-info">
                  <th>
                    idLectura
                  </th>
                  <th>
                    idSensor
                  </th>
                  <th>
                    Fecha
                  </th>
                  <th>
                    Hora
                  </th>
                  <th>
                    Estado
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      1
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                  <tr>
                    <td>
                      2
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                  <tr>
                    <td>
                      3
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                  <tr>
                    <td>
                      4
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-28
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                  <tr>
                    <td>
                      5
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-29
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                  <tr>
                    <td>
                      6
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-30
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Abierto
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>  
    <div class="col-md-12">
        <div class="card" id="tablaTemperaturas">
          <div class="card-header card-header-info">
            <h4 class="card-title ">Temperaturas</h4>
            <p class="card-category"> Registro de temperaturas</p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class=" text-info">
                  <th>
                    idTemp
                  </th>
                  <th>
                    idSensorT
                  </th>
                  <th>
                    fecha
                  </th>
                  <th>
                    hora
                  </th>
                  <th>
                    valor
                  </th>
                  <th>
                    estatus
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      1
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      20.15
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      2
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      20.15
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      3
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      23.50
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      4
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:45:10
                    </td>
                    <td>
                      22.00
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      5
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      25.23
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      6
                    </td>
                    <td>
                      2
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      19.15
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card"id="tablaHumos">
          <div class="card-header card-header-info">
            <h4 class="card-title ">Alertas Humo</h4>
            <p class="card-category"> Registro alertas de humo</p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class=" text-info">
                  <th>
                    idLectura
                  </th>
                  <th>
                    idSensor
                  </th>
                  <th>
                    Fecha
                  </th>
                  <th>
                    Hora
                  </th>
                  <th>
                    Estatus
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      1
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      2
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      3
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      4
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:45:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      5
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                  <tr>
                    <td>
                      6
                    </td>
                    <td>
                      2
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      Ok
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card" id="tablaPesos">
          <div class="card-header card-header-info">
            <h4 class="card-title ">Pesos</h4>
            <p class="card-category"> Registro de pesos</p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class=" text-info">
                  <th>
                    idTemp
                  </th>
                  <th>
                    idBascula
                  </th>
                  <th>
                    Fecha
                  </th>
                  <th>
                    Hora
                  </th>
                  <th>
                    Valor
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      1
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      20.15
                    </td>
                  </tr>
                  <tr>
                    <td>
                      2
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      20.15
                    </td>
                  </tr>
                  <tr>
                    <td>
                      3
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:41:10
                    </td>
                    <td>
                      23.50
                    </td>
                  </tr>
                  <tr>
                    <td>
                      4
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:45:10
                    </td>
                    <td>
                      22.00
                    </td>
                  </tr>
                  <tr>
                    <td>
                      5
                    </td>
                    <td>
                      1
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      25.23
                    </td>
                  </tr>
                  <tr>
                    <td>
                      6
                    </td>
                    <td>
                      2
                    </td>
                    <td>
                      2023-03-27
                    </td>
                    <td>
                      23:51:10
                    </td>
                    <td>
                      19.15
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  @endsection